### ISSUE TITLE
Unable to send a transaction signed on an offline node; fix create raw transaction so we are able to send on offline node

### ISSUE THREAD

**Issue by eb08a167** [zcash/zcash#3327]
### Describe the issue
There is an error when signing a transaction on an offline node as described at https://bitcoin.org/en/developer-examples#offline-signing.

#### If so, please list the steps to reproduce below:
1. Setup an online node with the following zcash.conf. Continue once it's fully synced.
```
testnet=1
disablewallet=0
server=1
rpcuser=foo
rpcpassword=bar
rpcallowip=0.0.0.0/0
rpcallowip=::/0
rpcport=8762
printtoconsole=1
```
2. Make sure there is at least one UTXO and run the following commands to build an unsigned transaction. I included my results.
```shell
$ zcash-cli listunspent
[
  {
    "txid": "a4fca062739f85a98b56e985e930b1174a1eb52873b35d94ef754d779923dc3f",
    "vout": 1,
    "generated": false,
    "address": "tmRTaMngZ81K44GyGpPjqajmdkB9NLWirj4",
    "account": "",
    "scriptPubKey": "76a914acb6a5f2de3f6859daddccda56c9903c1623b56d88ac",
    "amount": 2.99900000,
    "confirmations": 1,
    "spendable": true
  }
]

$ zcash-cli getaddressesbyaccount ""
[
  "tmQHbuXodHL8mZtUsw8dYXxbcgS6PFo8rSd",
  "tmRTaMngZ81K44GyGpPjqajmdkB9NLWirj4"
]

$ zcash-cli dumpprivkey tmRTaMngZ81K44GyGpPjqajmdkB9NLWirj4
cSXVP4HVBkW4cSoV2kv9F5jWz9gfRTwxJAW5gVA8uPGENyjz9CXU

$ zcash-cli createrawtransaction '[{"txid": "a4fca062739f85a98b56e985e930b1174a1eb52873b35d94ef754d779923dc3f", "vout": 1}]' '{"tmQHbuXodHL8mZtUsw8dYXxbcgS6PFo8rSd": "2.998"}'
030000807082c403013fdc2399774d75ef945db37328b51e4a17b130e985e9568ba9859f7362a0fca40100000000ffffffff01c095de11000000001976a9149fdba78a88de72be825a80fc6de4ad239a03851588ac0000000074ca030000
```
3. Switch to an offline node with the following zcash.conf. It doesn't have to be fully synced.
```
testnet=1
disablewallet=0
server=1
rpcuser=foo
rpcpassword=bar
rpcallowip=0.0.0.0/0
rpcallowip=::/0
rpcport=8762
printtoconsole=1
maxconnections=0
```
4. Sign the transaction from the 2nd step.
```shell
$ zcash-cli signrawtransaction 030000807082c403013fdc2399774d75ef945db37328b51e4a17b130e985e9568ba9859f7362a0fca40100000000ffffffff01c095de11000000001976a9149fdba78a88de72be825a80fc6de4ad239a03851588ac0000000074ca030000 '[{"txid": "a4fca062739f85a98b56e985e930b1174a1eb52873b35d94ef754d779923dc3f", "vout": 1, "scriptPubKey": "76a914acb6a5f2de3f6859daddccda56c9903c1623b56d88ac"}]' '["cSXVP4HVBkW4cSoV2kv9F5jWz9gfRTwxJAW5gVA8uPGENyjz9CXU"]'
{
  "hex": "030000807082c403013fdc2399774d75ef945db37328b51e4a17b130e985e9568ba9859f7362a0fca4010000006b483045022100ba4a8a53511842c41bc7883733bbb66e1cf51377ef6b72bf89c5424601b47e0702206586793dd0ad460f3632de6894eeb2be77cd007ba9bf017fc7d0ecc39befba19012102674cafc2d1afba93a76398e045e1cca26a822618f6201725e7f7941539a1c8cbffffffff01c095de11000000001976a9149fdba78a88de72be825a80fc6de4ad239a03851588ac0000000074ca030000",
  "complete": true
}
```
5. Switch back to the online node and send the transaction from the previous step.
```shell
$ zcash-cli sendrawtransaction 030000807082c403013fdc2399774d75ef945db37328b51e4a17b130e985e9568ba9859f7362a0fca4010000006b483045022100ba4a8a53511842c41bc7883733bbb66e1cf51377ef6b72bf89c5424601b47e0702206586793dd0ad460f3632de6894eeb2be77cd007ba9bf017fc7d0ecc39befba19012102674cafc2d1afba93a76398e045e1cca26a822618f6201725e7f7941539a1c8cbffffffff01c095de11000000001976a9149fdba78a88de72be825a80fc6de4ad239a03851588ac0000000074ca030000
error code: -26
error message:
16: mandatory-script-verify-flag-failed (Script evaluated without error but finished with a false/empty top stack element)
```

### Expected behaviour
The transaction is successfully broadcasted. Its TXID is obtained.

### Actual behaviour + errors
`sendrawtransaction` fails with `mandatory-script-verify-flag-failed (Script evaluated without error but finished with a false/empty top stack element)` error message. I performed the steps above with the latest Bitcoin Core (except it had addresstype=legacy in its conf file) and it worked.

### The version of Zcash you were using:
Zcash Daemon version v1.1.0-42e302523-dirty

### Machine specs:
- OS: Arch Linux, latest:
- CPU: Intel® Core™ i7-7700HQ CPU @ 2.80GHz × 8
- RAM: 15.5 GiB
- Disk size: 502.7 GB
- Disk Type (HD/SDD): SSD
- Linux kernel version (uname -a): Linux archlinux 4.16.13-1-ARCH #1 SMP PREEMPT Thu May 31 23:29:29 UTC 2018 x86_64 GNU/Linux
- Compiler version (gcc -version): gcc version 8.1.0 (GCC)

**Comment by garethtdavies** [comment]
This appears to be the same issue as https://github.com/zcash/zcash/issues/3280

**Comment by karel-3d** [comment]
We think this is happening with transactions generated on Trezor. (see linked issue)

**Comment by karel-3d** [comment]
cc @prusnak

**Comment by brucexiu** [comment]
when you signrawtransaction， output amount should be specified

**Comment by karel-3d** [comment]
@brucexiu no?

This is 1.1.1 rpc docs, when I look at testnet, it looks the same. There is no output amount.

https://zcash-rpc.github.io/signrawtransaction.html

**Comment by brucexiu** [comment]
The sample has no output amount, but  it's required in detail. If you don't pass amount, you will get a wrong signature hash.

`if (nIn != NOT_AN_INPUT){`
            `// The input being signed (replacing the scriptSig with scriptCode + amount)`
            `// The prevout may already be contained in hashPrevout, and the nSequence`
            `// may already be contained in hashSequence.`
            `ss << txTo.vin[nIn].prevout;`
            `ss << static_cast<const CScriptBase&>(scriptCode);`
            `ss << amount;`               It's **zero**
            `ss << txTo.vin[nIn].nSequence; `

Arguments:
1. "hexstring"     (string, required) The transaction hex string
2. "prevtxs"       (string, optional) An json array of previous dependent transaction outputs
     [               (json array of json objects, or 'null' if none provided)
       {
         "txid":"id",             (string, required) The transaction id
         "vout":n,                  (numeric, required) The output number
         "scriptPubKey": "hex",   (string, required) script key
         "redeemScript": "hex",   (string, required for P2SH) redeem script
         "amount": value            (numeric, **# required**) The amount spent
       }

**Comment by karel-3d** [comment]
Oh OK. My bad

**Comment by bitcartel** [comment]
@eb08a167 "Switch to an offline node with the following zcash.conf. It doesn't have to be fully synced."

Please try switching to an offline node, which is synced on testnet, at least past the point Overwinter has activated, and use the node to sign.

Do you still run into the problem?

**Comment by Eirik0** [comment]
Another option might be to add ```nuparams=5ba81b19:HEIGHT``` (where HEIGHT is some height that you have synced to) to the zcash.conf file. This should force Overwinter activation.

**Comment by eb08a167** [comment]
@bitcartel, thanks for the suggestion. I was able to sign and successfully broadcast a transaction. It turns out that an offline node has to be synced in order to properly sign a transaction. I also had to specify the amount field as @brucexiu said.

However, pre syncing an offline node doesn't look like an option for me. I believe one should be able to sign a transaction without the need to keep blockchain data.

**Comment by jasondavies** [comment]
Can someone clarify why an offline node would need to be synced, other than to obtain the input amount?  If the input amount is provided, I'm not sure I see why syncing should be necessary for offline signing.

**Comment by Eirik0** [comment]
It's because we are now using the amount as part of the
signature/verification. If the node is not synced then it does not know
that it should be signing in overwinter mode. It will then sign the old way
and not match the signature when trying to send the transaction from an
overwintered node.

**Comment by Eirik0** [comment]
Yes, this is all correct.

Regarding supporting it, I am neutral. I should be relatively
straight-forward to create a thirdparty tool to do the signing based on the
overwinter spec. It should also be straight-forward to add a parameter to
the signrawtransaction. I couldn't say which options would be more work for
whom.

**Comment by eb08a167** [comment]
@Eirik0, thanks!

>If the node is not synced then it does not know that it should be signing in overwinter mode.

An overwintered transaction has a bumped version. This can be used as an indicator whether to sign the transaction in overwinter mode or not. Am I right?

**Comment by daira** [comment]
Yeah this appears to be just a zcashd bug; ``createrawtransaction`` should use the height by default to determine whether to create an Overwinter tx, but ``signrawtransaction`` should use the version instead.

**Comment by Stayji** [comment]
@Eirik0, @daira, Hi, I use tool written by me, it is using the same algorithm which you use in signrawtransaction, I have fully synchronized node, but when I tried to use my tool for signing transaction and to broadcast one using rpc call of method `sendrawtransaction` I got error: `-26: 16: mandatory-script-verify-flag-failed (Script evaluated without error but finished with a false/empty top stack element)`  what am I doing wrongly? 
hex of signed tx: 
"030000807082c40302c87b207016aae28bd09eae4e6b1db89376826fae6a9a8888e99fa07baea10d72020000006a47304402207334f003c5074218f8f1751b16fbd223796912313ef3b206ac61117ae48b20f702200f394e025bfb7f0307ee9db625cd74c5d21c793a74da497924fd695517f215780121022aeb1e9a988de1ad0b1ab72c8623c8eacfced4a76ab2d0751de326e238082021ffffffff9feb15dffdd41473568bef6a77f30034b6f9fb29d570f89b556ff197f7eec4ed000000006a4730440220126e1e9e3635f725a3fab30c9a70a71d4837ca18259381af7d431f6b646f9955022038963e57526193aa3d2a0061a200818674323b8e25a79f7916bb88ea6e1f7f920121029cd4344a47d9efd07a9d15b5910d2f2adf5418f24b8b8ebb6a858b0937e729ffffffffff0328230000000000001976a91457b89f5234568819e3762e201d98508537e7d6ca88ac68c06800000000001976a914ff7a9bd74229f30e66b7ca40fba631eab97a8c3c88ac18652d00000000001976a914fa07e061df52fd5cf0a7e3c3d7d48dca2f91076f88ac00000000e484050000"

**Comment by colinrmoody** [comment]
Any updates here? Having this as an option in createrawtransaction() would be very useful

**Comment by colinrmoody** [comment]
Is there any other way to send a transaction signed offline?

**Comment by str4d** [comment]
Mis-click, sorry 😅

**Comment by ioptio** [comment]
@eb08a167 this should be fixed in the now released 2.0.1. Please upgrade and let us know whether it's fixed or not.

**Comment by eb08a167** [comment]
@ioptio, yep, it's working now. Thanks everybody!

**Comment by studyjavapython** [comment]
Can someone help me?I still can't fix it. My rawtransaction is '0400008085202f8901d4d9f9a9bdc8d23ab21949b9b12be0c72424cefcc2e87f3d8c95163bbe355cb4000000006a47304402201851fad701881ca8b381f29d65a0d50c544b98756621e35bc7f3046671d07c4302203dcf4310e71af789ce5320634358361e70fcc16c25d5b26e384bc48d5836ae6701210292e6b070b6198bc3a796273141c9c519df1bc6100d0a983a92549a20e103cb72ffffffff02402fa400000000001976a9147f42f222dc0935eb10b182ebb66153b66eaeef0488ac10270000000000001976a9146ba6742e3e976eda5a012e2432b46b954b60eaa088ac00000000ff64cd1d0000000000000000000000',after decode it,i can't see any error, but when I send the raw, it will response '16: mandatory-script-verify-flag-failed (Script evaluated without error but finished with a false/empty top stack element)'

**Comment by Eirik0** [comment]
@studyjavapython The error `16: mandatory-script-verify-flag-failed (Script evaluated without error but finished with a false/empty top stack element)` is generic and could be caused by a few different things. Assuming that you are on the latest version it is unlikely that it is the same error as described in this ticket. Do you mind creating a new issue with the above and any additional information that may be relevant? We will look at it soon.
